/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    GcalConnectCard: typeof import('./components/GcalConnectCard.vue')['default']
    LayoutSidebar: typeof import('./components/LayoutSidebar.vue')['default']
    LogosGoogleCalendar: typeof import('~icons/logos/google-calendar')['default']
    MaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    MaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    MaterialSymbolsEventNote: typeof import('~icons/material-symbols/event-note')['default']
    MaterialSymbolsPause: typeof import('~icons/material-symbols/pause')['default']
    MaterialSymbolsPlayArrow: typeof import('~icons/material-symbols/play-arrow')['default']
    MaterialSymbolsRestartAlt: typeof import('~icons/material-symbols/restart-alt')['default']
    MaterialSymbolsSchedule: typeof import('~icons/material-symbols/schedule')['default']
    MaterialSymbolsScheduleOutline: typeof import('~icons/material-symbols/schedule-outline')['default']
    MaterialSymbolsSkipNext: typeof import('~icons/material-symbols/skip-next')['default']
    MaterialSymbolsStarRounded: typeof import('~icons/material-symbols/star-rounded')['default']
    PomodoroWindow: typeof import('./components/PomodoroWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedSubtitle: typeof import('./components/SharedSubtitle.vue')['default']
    TaskCreateDialog: typeof import('./components/TaskCreateDialog.vue')['default']
    TaskEditDialog: typeof import('./components/TaskEditDialog.vue')['default']
    TaskFocusDialog: typeof import('./components/TaskFocusDialog.vue')['default']
    TaskItem: typeof import('./components/TaskItem.vue')['default']
    TaskList: typeof import('./components/TaskList.vue')['default']
    TaskNoteInput: typeof import('./components/TaskNoteInput.vue')['default']
    TaskTitleInput: typeof import('./components/TaskTitleInput.vue')['default']
    TheSidebar: typeof import('./components/TheSidebar.vue')['default']
    TimeGridDay: typeof import('./components/TimeGridDay.vue')['default']
  }
}
