/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomToolbar: typeof import('./components/BottomToolbar.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    SharedSubtitle: typeof import('./components/SharedSubtitle.vue')['default']
    TaskEditor: typeof import('./components/TaskEditor.vue')['default']
    TaskInput: typeof import('./components/TaskInput.vue')['default']
    TaskItem: typeof import('./components/TaskItem.vue')['default']
    TaskList: typeof import('./components/TaskList.vue')['default']
  }
}
