/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomToolbar: typeof import('./components/BottomToolbar.vue')['default']
    LayoutSidebar: typeof import('./components/LayoutSidebar.vue')['default']
    MaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    MaterialSymbolsPauseCircle: typeof import('~icons/material-symbols/pause-circle')['default']
    MaterialSymbolsPlayCircle: typeof import('~icons/material-symbols/play-circle')['default']
    MaterialSymbolsPlayCircleOutline: typeof import('~icons/material-symbols/play-circle-outline')['default']
    MaterialSymbolsReplayCircleFilled: typeof import('~icons/material-symbols/replay-circle-filled')['default']
    MaterialSymbolsScheduleOutline: typeof import('~icons/material-symbols/schedule-outline')['default']
    MaterialSymbolsStarRounded: typeof import('~icons/material-symbols/star-rounded')['default']
    MaterialSymbolsTag: typeof import('~icons/material-symbols/tag')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedSubtitle: typeof import('./components/SharedSubtitle.vue')['default']
    TaskCreateDialog: typeof import('./components/TaskCreateDialog.vue')['default']
    TaskEditDialog: typeof import('./components/TaskEditDialog.vue')['default']
    TaskFocusDialog: typeof import('./components/TaskFocusDialog.vue')['default']
    TaskItem: typeof import('./components/TaskItem.vue')['default']
    TaskList: typeof import('./components/TaskList.vue')['default']
    TaskNoteInput: typeof import('./components/TaskNoteInput.vue')['default']
    TaskTitleInput: typeof import('./components/TaskTitleInput.vue')['default']
  }
}
